language: php

php:
- '7.0'
- '5.6'

env:
  global:
    - WP_ERROR_LOG=/tmp/wp-error.log
  matrix:
    - WP_VERSION=nightly WP_THEME=twentysixteen WP_PATH=/tmp/wp-tests
    - WP_VERSION=latest WP_THEME=twentysixteen WP_PATH=/tmp/wp-tests

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - npm run init
  - npm run install-wp
  - npm run wp >/dev/null 2>&1 &

script:
  - npm test
