language: php

php:
- '7.0'

env:
  global:
    - WP_ERROR_LOG=/tmp/wp-error.log
    - WP_VERSION=latest
    - WP_PATH=/tmp/wp-tests
  matrix:
    - WP_THEME=https://wordpress.org/themes/download/vanilla.1.2.2.zip?nostats=1

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - npm run init
  - npm run install-wp
  - npm run wp >/dev/null 2>&1 &

script:
  - npm test
