language: php

php:
- '7.0'
- '5.6'

env:
  matrix:
    - WP_PATH=/tmp/wp-behat-tests WP_VERSION=nightly WP_THEME=twentyseventeen
    - WP_PATH=/tmp/wp-behat-tests WP_VERSION=latest WP_THEME=twentysixteen

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - npm run init
  - npm run install-wp
  - npm run wp >/dev/null 2>&1 &
  - ./wp-cli-nightly.phar plugin install https://github.com/miya0001/theme-meta-api/archive/master.zip --activate --path=$WP_PATH

script:
  - npm test
